/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    "inline-flex",
    "items-center",
    "justify-center",
    "justify-start",
    "gap-2",
    "whitespace-nowrap",
    "rounded-md",
    "rounded-xl",
    "border",
    "border-input",
    "border-transparent",
    "bg-primary",
    "bg-secondary",
    "bg-background",
    "bg-card",
    "text-primary",
    "text-primary-foreground",
    "text-secondary-foreground",
    "text-card-foreground",
    "text-muted-foreground",
    "text-foreground",
    "shadow",
    "shadow-sm",
    "text-sm",
    "text-xs",
    "font-medium",
    "font-semibold",
    "transition-colors",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-ring",
    "focus:ring-offset-2",
    "focus-visible:outline-none",
    "focus-visible:ring-1",
    "focus-visible:ring-ring",
    "disabled:pointer-events-none",
    "disabled:opacity-50",
    "hover:bg-primary/80",
    "hover:bg-primary/90",
    "hover:bg-secondary/80",
    "hover:bg-accent",
    "hover:text-accent-foreground",
    "h-8",
    "h-9",
    "h-10",
    "w-9",
    "px-2.5",
    "px-3",
    "px-4",
    "px-8",
    "py-0.5",
    "py-2",
    "p-6",
    "pt-0",
    "flex",
    "flex-col",
    "space-y-1.5",
    "leading-none",
    "relative",
    "overflow-hidden",
    "h-full",
    "w-full",
    "rounded-[inherit]",
    "touch-none",
    "select-none",
    "w-2.5",
    "border-l",
    "border-l-transparent",
    "h-2.5",
    "border-t",
    "border-t-transparent",
    "p-[1px]",
    "flex-1",
    "rounded-full",
    "bg-border",
    "w-4",
    "h-4",
    "w-8",
    "border-2",
    "border-4",
    "border-t-accent",
    "border-white",
    "animate-spin",
    "[&_svg]:pointer-events-none",
    "[&_svg]:size-4",
    "[&_svg]:shrink-0",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}

